name: CI

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: windows-latest
    name: Dotner build
    steps:
     - uses: actions/checkout@master
     - name: Setup dotnet
       uses: actions/setup-dotnet@v1
       with:
          dotnet-version: '3.1.100' # SDK Version to use.
     - run: dotnet build DNB.QAInterview.csproj
